### ISSUE TITLE
LiveData.observe()中出现异常无法继续接收数据的问题

### ISSUE THREAD

**Issue by iotxc** [aleyn97/MVVMLin#27]
博主，使用你的封装方法后出现了如下问题：

![viewmodel](https://user-images.githubusercontent.com/23256376/126460606-a38f40c6-a48a-4542-b394-e61c355100cd.png)

![main_view_model](https://user-images.githubusercontent.com/23256376/126460923-dc1d130e-3d32-45cc-a4ea-1f513bc52860.png)

![mian_activity](https://user-images.githubusercontent.com/23256376/126460944-08cea548-ccb2-4ec2-860d-ae4b5156075d.png)

在触发Exception之后程序并没有崩溃，这个Exception走到了BaseViewModel#handleException的catch中，但是后面再去setValue时，ui就收不到通知了

![LiveData](https://user-images.githubusercontent.com/23256376/126461141-e85e2cc2-726e-4c51-bcdb-155fe6fccb0b.png)

调试发现后面这个mDispatchingValue一直为true，博主知道怎么解决嘛？

**Comment by aleyn97** [comment]
现在不推荐 CallBack 的形式了，看下最新代码吧
